rootProject.name = 'thawani_flutter'
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Add this line here
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/ThawaniMobile/Lamsa-SDK")
            credentials {
                username = "ThawaniMobile"
                password = "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"
            }
        }
    }
}